### ISSUE TITLE
Einige Modulnamen erzeugen Error 

### ISSUE THREAD

**Issue by cukabeka** [cukabeka/REX_Themesync#2]
> Warning: ftp_chdir() [function.ftp-chdir]: /modules/Multinewsletter Anmeldeformular: Datei oder Verzeichnis nicht gefunden in /redaxo/src/addons/themesync/lib/ftp_client.php on line 81

Nicht alle Module in der REX-Instanz werfen diesen Error, kann nicht genau Erkennen, woran es liegt. Auffällig viele, aber nicht alle haben ein "-" im Namen.

**Comment by stefan-beyer** [comment]
Ohne weitere Analyse habe ich die Leerzeichen in Verdacht. Ich bin ja der Meinung, Ordnernamen in diesem Kontext sollten keine Leerzeichen enthalten... Der schnellste Weg könnte also zunächst das Entfernen der Leerzeichen sein.

Alles andere muss ich erst recherchieren. z.B. [hier](https://stackoverflow.com/questions/25518069/using-ftp-get-when-there-are-spaces-in-the-file-path-and-filename)

**Comment by stefan-beyer** [comment]
Falls das Entfernen der Leerzeichen nicht hilft, brauche ich eine genauere Liste der Namen, die zu einem Fehler führen (und eine der funktionierenden). Bei mir funktionieren Ordnernamen mit Leerzeichen ohne Probleme.

**Comment by stefan-beyer** [comment]
Es handelt sich wohl lediglich um die Warnung, die ftp_chdir meldet, wenn ein Ordner auf dem FTP-Server nicht existiert. Das passiert für jedes Modul, dass lokal vorhanden, aber nicht im Repo ist. Wird jetzt mit dem @-Operator unterdrückt. Neue Methode `rex_themesync_ftp_client::dir_exists()` kapselt das.
