### ISSUE TITLE
Install aus repo schlägt fehl

### ISSUE THREAD

**Issue by cukabeka** [cukabeka/REX_Themesync#3]
Error
Call to a member function get() on null
   
Stack frames (15)
14
Error 
…/redaxo/src/addons/themesync/lib/ftp_client.php119
13
rex_themesync_ftp_client get_contents
…/redaxo/src/addons/themesync/lib/repo_ftp.php69
12
rex_themesync_repo_ftp getFileContents
…/redaxo/src/addons/themesync/lib/repo.php53
11
rex_themesync_repo loadModuleInputOutput
…/redaxo/src/addons/themesync/lib/module.php44
10
rex_themesync_module loadInputOutput
…/redaxo/src/addons/themesync/lib/module.php35
9
rex_themesync_module getInput
…/redaxo/src/addons/themesync/lib/local.php148
8
rex_themesync_local installModule
…/redaxo/src/addons/themesync/lib/module_manager.php99
7
rex_themesync_module_manager action
…/redaxo/src/addons/themesync/pages/modules.php6
6
 include
…/redaxo/src/addons/themesync/pages/index.php16
5
 include
…/redaxo/src/core/lib/packages/package.php228
4
rex_package includeFile
…/redaxo/src/core/lib/be/controller.php456
3
rex_be_controller includePath
…/redaxo/src/core/lib/be/controller.php403
2
rex_be_controller includeCurrentPage
…/redaxo/src/core/backend.php146
1
 require
…/redaxo/src/core/boot.php125
0
 require
…/redaxo/index.php9

**Comment by stefan-beyer** [comment]
Commit sollte den bug fixen.
